name       : python-random2
version    : 1.0.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/r/random2/random2-1.0.1.zip : 34ad30aac341039872401595df9ab2c9dc36d0b7c077db1cea9ade430ed1c007
homepage   : https://pypi.org/project/random2/
license    : PSF-2.0
component  : programming.python
summary    : Python 3 compatible Python 2 `random` Module
description: |
    This package provides a Python 3 ported version of Python 2.7’s random module.
setup      : |
    %patch -p1 < $pkgfiles/fix-tests-with-python-3.9
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
